# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael Price
email: michaelprise@gmail.com@gmail.com
description: Fun fun things
baseurl: "https://michaelprise.github.io" # the subpath of your site, e.g. /blog
url: "https://michaelprise.github.io" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/logo.svg
font-awesome-icon-logo:

# Social settings

twitter_username: andrewbanchich
facebook_URL: andrewbanchich
instagram_username: andrewbanchich
dribbble_username: andrewbanchich
500px_username: andrewbanchich
phone: 555-5555

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
